### ISSUE TITLE
May needs adapt to Android 12

### ISSUE THREAD

**Issue by erbanku** [nfcim/nfsee#12]
I can add my campus card normally, but unable to use it due to the system does not opening the nfsee app when I swipe it. I looked into the NFC settings and found that nfsee app was not recognized correctly, so unable to set it default, moreover unable to use the app function normally.

<details>
<summary>Details Screenshot</summary>

![WeChat Image_20220902095453](https://user-images.githubusercontent.com/79493862/188042217-045f1dad-ca97-4c20-96f5-22ee7dbce0c6.jpg)

</details>

**Comment by dangfan** [comment]
Currently, we are using the foreground reader mode, which is not compatible with background polling.
BTW, the screenshot you provided is for card emulation. It's a totally different use case.

**Comment by erbanku** [comment]
But when I try to use the app in foreground and swipe to the card reader, the app automatically jumps to the system preinstalled wallet app, and unable function normally.

**Comment by erbanku** [comment]
I am using the app with Tsinghua University Student Campus Card.

**Comment by dangfan** [comment]
> But when I try to use the app in foreground and swipe to the card reader, the app automatically jumps to the system preinstalled wallet app, and unable function normally.

That's right. NFSee and the used NFC library (flutter_nfc_kit) leverage [Foreground Dispatch](https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc#foreground-dispatch). Therefore, you have to click the Polling button before tapping your card.

**Comment by erbanku** [comment]
> > But when I try to use the app in foreground and swipe to the card reader, the app automatically jumps to the system preinstalled wallet app, and unable function normally.
> 
> That's right. NFSee and the used NFC library (flutter_nfc_kit) leverage [Foreground Dispatch](https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc#foreground-dispatch). Therefore, you have to click the Polling button before tapping your card.

Sorry, but which is Pooling button you mentioned, I have no idea how to use it now. Can you explain it a bit more

**Comment by dangfan** [comment]
> > > But when I try to use the app in foreground and swipe to the card reader, the app automatically jumps to the system preinstalled wallet app, and unable function normally.
> > 
> > 
> > That's right. NFSee and the used NFC library (flutter_nfc_kit) leverage [Foreground Dispatch](https://developer.android.com/guide/topics/connectivity/nfc/advanced-nfc#foreground-dispatch). Therefore, you have to click the Polling button before tapping your card.
> 
> Sorry, but which is Pooling button you mentioned, I have no idea how to use it now. Can you explain it a bit more? Thanks.

Just click the "+" at the up-right corner as shown below.
![IMG_70E634AF317B-1](https://user-images.githubusercontent.com/1330913/188138758-983f1054-2786-48e5-a11e-06e07a23d8fb.jpeg)

**Comment by erbanku** [comment]
I already added it successfully, I am going to use it to swipe the door & ATU（阿荼）and canteen meal fee. Just replace the campus card with phone.

<details>
<summary>Details</summary>

![WeChat Image_20220902200458](https://user-images.githubusercontent.com/79493862/188139246-ba2c5f68-9c0c-4320-885d-6c3fbb16a81b.jpg)


</details>

**Comment by dangfan** [comment]
> I already added it successfully, I am going to use it to swipe the door & ATU（阿荼）and canteen meal fee. Just replace the campus card with phone.
> 
> Details
> ![WeChat Image_20220902200458](https://user-images.githubusercontent.com/79493862/188139246-ba2c5f68-9c0c-4320-885d-6c3fbb16a81b.jpg)

Unfortunately, NFSee is a tool for reading cards only. BTW, emulating the Tsinghua Campus Card is impossible.

**Comment by erbanku** [comment]
OK, thanks a lot.
