### ISSUE TITLE
Will it work For iOS

### ISSUE THREAD

**Issue by sreekanthps** [nfcim/nfsee#16]
Did not see the app for iOS..  Will it work for iOS ?

**Comment by sreekanthps** [comment]
And android app also not working .. it does not show any thing in app when i tap my NFC enabled credit card

**Comment by jiegec** [comment]
> Did not see the app for iOS.. Will it work for iOS ?

You can find NFSee on App Store

**Comment by sreekanthps** [comment]
I tired using iOS app., Nothing shows for payment card. For non payment cards atleast it shows error (screen shot attached)
![image_123986672](https://user-images.githubusercontent.com/6374791/206627483-57a38171-e4ad-472d-ad86-7bda98bec2a4.JPG)

Android also the read is inconsistent. Out of 10 times only 1 time it worked

**Comment by jiegec** [comment]
Please refer to README.md for a list of supported cards.
