### ISSUE TITLE
Scanning card bricks history

### ISSUE THREAD

**Issue by axelsimon** [nfcim/nfsee#20]
Hello,
If i scan my bank card, it renders the history unusable.

The history looks empty, says "No history find" and under "Scan history" some Chinese characters appear:
![Imagepipe_29](https://github.com/nfcim/nfsee/assets/1172256/92a4e844-f58e-4135-b109-e6cffe22c19a)

Strangely, if i go into settings and delete data, i can see that the records are still there: right now it says "Record count: 7".

So something happens when reading certain cards that bricks NFSee's ability to display history.

**Comment by infinity0** [comment]
Same here. The error prevents you from scanning any further cards, until you go into android App Info settings and clear both Storage and Cache. Then you lose all your previous scanned cards, but you can try scanning again.

The bug happens randomly, even with the same card. The bug happens ~0% of the time with my T-Union China Transport card, about ~60% of the time with my UK Visa cards, and about ~100% of the time with my UK MasterCard card.

The Chinese characters mean "downloading..." which might sound a bit dodgy, luckily my firewall blocks all applications until I explicitly allow it. However even if I wanted to, I am unable to allow this app internet access - neither this app nor "NFC Reader" (com.github.muellerma.nfcreader) show up in the list of applications on my VPN app (OpenVPN for Android) or my firewall app (AFWall+) but they do show up in the system "App Info" settings. Weird.

**Comment by Harry-Chen** [comment]
Thanks for your report! "加载中" actually means "loading", not "downloading". So there must be some problem parsing the data read from your bank card. 

Could you inform us on the the of card that you try to read?

**Comment by infinity0** [comment]
As above:

> The bug happens randomly, even with the same card. The bug happens ~0% of the time with my T-Union China Transport card, about ~60% of the time with my UK Visa cards, and about ~100% of the time with my UK MasterCard card.

I tried it again with my UK MasterCard card and it worked once, and failed several more times.

It seems to work fine (~0% bug) with my UK oyster (transport) card.

I'm holding the card close to my phone exactly the same in all cases.

Regardless of the type of card, if NFSee doesn't recognise it, or if there is an error in reading, regardless of any of this, there should be no possible logic path in the code that bricks the app like this. It is certainly possible to fix this bug without having any of these cards available to you as a developer.

**Comment by infinity0** [comment]
> "加载中" actually means "loading", not "downloading".

My bad, my brain quickly misread 加 the same way as 下.

**Comment by strangersdangers** [comment]
Any updates on this issue? This error is still occuring.

**Comment by pipcet** [comment]
Should be fixed by #26 , I think. However, this won't recover the bricked history. Let me know if you need that.
